In [28]:
using SparseArrays

spzeros(3, 1)

3×1 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅ 
  ⋅ 
  ⋅ 

In [7]:
spdiagm(0 => [1.0, 2.0, 3.0])

3×3 SparseMatrixCSC{Float64, Int64} with 3 stored entries:
 1.0   ⋅    ⋅ 
  ⋅   2.0   ⋅ 
  ⋅    ⋅   3.0

In [15]:
I_M = spdiagm(0 => ones(Float64, 5))

5×5 SparseMatrixCSC{Float64, Int64} with 5 stored entries:
 1.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅   1.0

In [17]:
spzeros(3, 3)

3×3 SparseMatrixCSC{Float64, Int64} with 0 stored entries:
  ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅ 

In [21]:
using LinearAlgebra

Matrix(1.0I, 4, 4)

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [5]:
A = Matrix(1.0I, 4, 4)
B = [A; A]

B[1, 1]

1.0

In [26]:
sparse(B)

8×4 SparseMatrixCSC{Float64, Int64} with 8 stored entries:
 1.0   ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅   1.0
 1.0   ⋅    ⋅    ⋅ 
  ⋅   1.0   ⋅    ⋅ 
  ⋅    ⋅   1.0   ⋅ 
  ⋅    ⋅    ⋅   1.0

In [34]:
foo(x::Float64)::Int64 = 1 + ceil(x);

foo(3.0)

4

In [41]:
sum(B, dims = 2)

8×1 Matrix{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [42]:
A

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0

In [ ]:
C = Array

In [3]:
mutable struct ProblemConditions
    η_k::Array{Float64}
    u_k::Array{Float64}
    z_k::Float64
    v_k::Float64
    P_k::Array{Float64}
    dt ::Float64
end

A = ProblemConditions([NaN], [NaN], NaN, NaN, [NaN], NaN)

ProblemConditions([NaN], [NaN], NaN, NaN, [NaN], NaN)

In [15]:
using LinearAlgebra


X = zeros((4,)); X[1] = 1;
println(typeof(X))

A = rand(4, 4)

b = A\X
println(norm(A*b- X))

Vector{Float64}
4.611102534756203e-16


In [54]:
XX = Array{Any}(undef, 3);  XX[2] = 0.1; 
println(XX[2])
println(isassigned(XX, 0))
println(XX)

0.1
false
Any[#undef, 0.1, #undef]


In [11]:
a = 1;

while a < 10
    println(a)
    local zero;
    a = a + 1;
    if a  == 2
        
        zero = 27;
    elseif a == 7
        println(zero);
    end
end


UndefVarError: UndefVarError: zero not defined